version: "3.5"

volumes:
  wordpress:
  mariadb:

networks:
  cNet:
    name: cNet

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - cNet
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - cNet
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - cNet
    restart: always
